# Site settings
title: Hanwei is feeding a dog
email: chuxiking@163.com
description: "Hello~~~,论程序员与文艺青年交汇的惰性."
baseurl: ""
url: "http://chuxi.github.io"

# Build settings
markdown: kramdown
permalink: pretty

