# Site settings
title: Hanwei Jin
email: chuxiking@163.com
description: Hello Hanwei.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http:chuxi.github.io" # the base hostname & protocol for your site

github_username:  chuxi

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
#  syntax_highlighter: rouge
  enable_coderay: true

gems:      [jekyll-paginate]
# pagination settings
paginate: 20